// KBBI baku words pool, grouped by length
export const WORDS: Record<number, string[]> = {
  3: ["air","api","abu","ada","aku","ayo","bom","bui","cat","cor","dia","dua","eja","eka","emas","gas","gua","hak","hal","hen","ide","ijo","ini","itu","jam","jas","kau","kue","lup","mau","nak","obi","pak","puk","rok","sah","tas","ubi","upa","vas","wah","yoi","zat","kau","ban","cap","duo","fee"],
  4: ["abad","adat","agar","agen","ajar","akal","alam","alat","amal","amin","anak","anda","aneh","apel","arah","arif","arus","asas","asin","asli","atap","aula","awan","ayah","ayam","baca","baju","baik","bait","balu","bara","baru","basi","bawa","bayi","beda","beli","beri","besi","biar","bibi","bila","biru","buah","buat","buka","bumi","bunga","cair","cara","ceri","cuci","daki","dana","dapa","data","daun","debu","dewa","dini","doa","duku","duri","duta","emas","enam","esok","fana","gaji","gara","gaya","gela","giat","gigi","gula","guru","habis","haji","hari","hati","hemat","hias","hidup","hujan","ilmu","ikan","ikat","ingat","istri","jala","jari","jauh","jiwa","kaca","kado","kain","kaki","kala","kami","kapa","kapan","kapur","kata","kaya","kebun","kelas","keluh","kena","kepala","keras","kerja","ketat","kuat","kuda","kuno","laba","lain","laju","laki","laku","lama","lampu","lapar","laut","lawan","lebar","lebih","lega","lemah","lembah","libur","lidah","lima","lipat","lupa","luput","luwes","mahal","mahir","main","maju","makan","makin","malam","manis","mata","mati","muda","mulai","mulia","mulut","nafas","naik","nama","nasi","nilai","nyala","obat","ojek","olah","orang","otak","padi","pagi","pahit","pakai","palsu","pamit","panas","pandai","panen","pantai","papan","pasar","pasir","payung","pedas","pedih","pekat","peluk","penat","pendek","peneliti","pergi","perak","peran","perang","permai","persen","pesan","peta","piala","pidato","pikir","pilar","pinta","pipi","pisau","pohon","polos","prima","prinsip","puji","pulang","pulau","pulih","punah","puncak","pundak","punya","pusat","puyuh","raih","rajin","ramah","ramai","rapat","rapi","rasa","reda","rela","rendah","reren","resep","ribu","ringan","riang","roti","rumah","rusak","saat","sabar","sadar","saji","saksi","saku","salam","salju","sama","sambil","sampai","sandar","sandi","sapu","sarat","satu","saudara","sayur","sebab","sedih","sehat","sejuk","seksi","selam","selisih","seluk","sembap","sempit","sempurna","sengaja","senja","sepuluh","seribu","setia","sewa","sigap","sikap","silam","singgah","sipit","siram","sirip","sisi","sopan","sosial","sudah","sukar","suluh","sumur","sungai","supir","surya","susah","susu","tabah","tahu","tajam","tali","taman","tanah","tangkap","tante","tanya","tapak","tari","tarik","tata","tawa","tayang","tebal","teduh","teh","tekan","telur","tema","temu","tempat","tendang","terang","terasa","terima","tetap","tiba","tidak","tidur","tiga","tikar","timbang","tinta","tirai","tirta","tisu","toko","tolak","tolong","tonggak","topi","tradisi","tradisional","tugas","tulis","tumbuh","tunda","tuntut","turun","tutur","ulang","umat","ungu","unik","untung","upah","urai","usaha","usia","utuh","vena","vokal","wajah","wajib","waktu","warna","warta","wibawa","yakin","yatim","zaman"],
  5: ["acara","adili","ajaib","akhir","alasan","amanah","amplop","angka","anjing","apresiasi","artis","asing","atlet","aturan","awal","ayunan","bahagia","bahasa","bajak","bakar","balas","banjir","bangsa","bantal","bantu","barat","baris","baruh","batas","bayar","bekas","beker","belai","belum","benar","benda","beruang","besar","bilang","bisik","bohong","bocah","brani","bukti","bunga","cabang","calon","cantik","cebok","celah","cepat","ceria","cerita","cetak","cinta","cipta","contoh","corak","cucu","cukup","damai","dapat","datang","dekat","derap","desas","dewasa","didik","dingin","dompet","dosen","dukun","duduk","dunia","emosi","empat","fakta","fitur","gagah","gajah","galau","gelap","gemar","genap","gigit","golem","gugur","gurih","habis","hadap","halal","hangat","harap","harum","hasil","hebat","hemat","hijau","hilir","hingga","hitam","hutan","ideal","impian","indah","induk","ingin","ingat","insan","iring","jadwal","jagat","jaman","jalin","jamur","jangan","jasmani","jelas","jejak","jenak","jerat","jujur","kabel","kabar","kakak","kalah","kanan","kantor","kapal","karib","karya","kasih","keadilan","kebal","kecil","kedai","kekal","kelana","kelola","kembar","kemudi","kenal","kepompong","kerasak","kering","ketika","kilang","kiriman","klinik","komik","kondisi","kotak","kreatif","kuasa","kucing","kuliah","kumis","kurang","langit","lapis","lautan","lemah","lemak","libur","limpah","lingkungan","lingga","logam","lukis","lunak","mabuk","macan","madat","makna","malam","manfaat","mandi","mantra","manusia","marah","masyarakat","matang","mereka","minum","modal","monyet","muara","mungkin","murah","murid","musim","nafsu","nakal","nakhoda","nasib","negeri","obrol","ombak","orang","padu","pagar","pakar","pakem","palak","panas","papan","pasak","pelita","peluang","pemilu","penyiar","perih","piala","piring","pintar","pintu","piring","puisi","pulau","punah","punya","rajin","ramah","raksasa","rapat","ratu","ribu","ritus","robot","ruang","rumah","sakit","sakti","salam","sandar","santai","sapaan","sarung","sayang","sedia","segar","sehat","sejarah","selalu","semangat","senyum","sepatu","serta","sesuai","setia","sigap","silam","sopan","sukses","sulit","tampil","tanah","tanaman","teman","tenang","terang","terjal","tinggi","tujuan","ulasan","umpan","ungkap","untuk","usaha","wajib","waktu","warna","warung","yakin","zaman"],
  6: ["aksara","amanat","ampuni","anggota","angkasa","arsitek","awalan","bahaya","baikan","balada","bangkit","banteng","barisan","baterai","bayangan","belajar","beranda","berikut","biduan","bijaksana","binatang","bintang","bisikan","budaya","cabang","cahaya","cakrawala","camilan","carian","catatan","ceramah","cermat","cermin","ceroboh","cipratan","corong","damping","dengung","derita","desain","desain","detail","dewata","diaspora","dilema","disket","ditolong","drama","duduki","dunia","ekspor","emosi","fajar","fasilitas","fenomena","filsafat","gairah","ganggu","gembira","genting","getaran","goresan","gotong","gulungan","halilintar","hampar","handal","harian","harmoni","hewani","hiasan","hibrida","horizon","ibadah","identitas","imbangi","inisiatif","inspirasi","inti","istimewa","jadwal","jajaran","jelajah","jendela","jeritan","jurusan","kakek","kalung","kamera","kapas","kasus","keajaiban","kebijakan","kecuali","kekasih","kelinci","kemana","kemarin","kembali","kemudahan","kepala","kerikil","keritik","kesan","ketat","ketela","kondom","kreatif","kreator","kritik","kuasa","kucing","kuil","kursus","langit","lapisan","laut","layanan","lemari","lentera","lestari","lilin","lipatan","lukisan","mahkota","makmur","mandiri","mantan","martabat","masakan","melekat","memaksa","menara","mendung","menulis","merdeka","misteri","model","monyet","murni","narasi","nilai","obyek","ombak","optimal","ornamen","pahlawan","pamer","panitia","papan","pasaran","penjual","penulis","peranan","perjalanan","pertama","pintar","piramida","politik","pondasi","prestasi","produk","puisi","pundak","raksasa","rambut","rangka","rapat","rasakan","raya","rektor","rencana","ribuan","rumput","saksama","sandiwara","sarjana","sayap","seleksi","sembah","semilir","sengaja","sentuh","sepatu","seragam","serikat","sesepuh","setara","setiap","sigap","sikap","sintesa","sosial","strategi","suasana","suka","syarat","tabuhan","tampilan","tantangan","teater","teladan","tempat","tenangi","terampil","tertawa","tetangga","tinggi","topeng","tradisi","tujuan","tukang","tunas","ujian","ungkapan","upacara","usaha","vaksin","wabah","wakil","warisan","wisata","yakini","zamrud"],
  7: ["adaptasi","aktivis","alkohol","amplitudo","anggaran","anugerah","apresiasi","arsitektur","asuransi","bagaimana","bandara","bangunan","bantuan","bencana","beraksi","berdampak","berharap","berkarya","beruang","biografi","budaya","capaian","cendekia","cetakan","damping","datangi","demokrasi","desainer","dialog","disiplin","dokumen","domain","ekosistem","ekspedisi","ekspresi","elemen","emosi","filsafat","fungsional","gemilang","generasi","geometri","gerakan","gradasi","harapan","harmoni","historis","horison","ideologi","imajinasi","inflasi","inovasi","integrasi","intuisi","jaminan","jelajahi","jendela","jurnalistik","kapasitas","karakter","kategori","kebangsaan","kebebasan","kedamaian","kekuatan","kemajuan","kenangan","keperluan","keragaman","kerajaan","kesatuan","keutuhan","kewajiban","kompetisi","komputer","kondisi","koridor","kreatif","kreativitas","kuliah","laboratorium","langkah","lapangan","laporan","logika","manajemen","martabat","matahari","melodi","menjelma","metode","misteri","modernitas","monitor","motivasi","narasi","navigasi","nominasi","nostalgia","optimisme","organisasi","panggung","peradaban","perancang","peristiwa","perjalanan","perubahan","piranti","produktif","produktivitas","program","prosedur","prototipe","provinsi","puisi","quantitas","raksasa","rancangan","rangkaian","reaksi","referensi","reformasi","relasi","relawan","relevan","rencana","representasi","sastra","sejarah","sejahtera","semesta","semilir","seragam","serikat","simfoni","singkat","sintesis","skenario","sosial","spektrum","strategi","struktur","sumbangsih","tabuhan","tahapan","tantangan","teknologi","temuan","teorema","terampil","tradisi","transformasi","ujian","ungkapan","universitas","upacara","vaksinasi","variasi","vegetasi","vertikal","visualisasi","wabah","waktu","warisan","wirausaha","yayasan","zamrud"],
};

const ALPHA = "abcdefghijklmnopqrstuvwxyz";

export function randomNonsense(len: number): string {
  let s = "";
  for (let i = 0; i < len; i++) s += ALPHA[Math.floor(Math.random() * ALPHA.length)];
  return s;
}

export function getRandomWord(level: number): string {
  // Length ramps with level
  const minLen = Math.min(7, 3 + Math.floor((level - 1) / 3));
  const maxLen = Math.min(7, 4 + Math.floor((level - 1) / 2));
  const len = minLen + Math.floor(Math.random() * (maxLen - minLen + 1));
  const pool = WORDS[len] ?? WORDS[4];
  return pool[Math.floor(Math.random() * pool.length)].toLowerCase();
}
