/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TypefallRouteImport } from './routes/typefall'
import { Route as RhythmRouteImport } from './routes/rhythm'
import { Route as MultiplayerRouteImport } from './routes/multiplayer'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as IndexRouteImport } from './routes/index'

const TypefallRoute = TypefallRouteImport.update({
  id: '/typefall',
  path: '/typefall',
  getParentRoute: () => rootRouteImport,
} as any)
const RhythmRoute = RhythmRouteImport.update({
  id: '/rhythm',
  path: '/rhythm',
  getParentRoute: () => rootRouteImport,
} as any)
const MultiplayerRoute = MultiplayerRouteImport.update({
  id: '/multiplayer',
  path: '/multiplayer',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/leaderboard': typeof LeaderboardRoute
  '/multiplayer': typeof MultiplayerRoute
  '/rhythm': typeof RhythmRoute
  '/typefall': typeof TypefallRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/leaderboard': typeof LeaderboardRoute
  '/multiplayer': typeof MultiplayerRoute
  '/rhythm': typeof RhythmRoute
  '/typefall': typeof TypefallRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/leaderboard': typeof LeaderboardRoute
  '/multiplayer': typeof MultiplayerRoute
  '/rhythm': typeof RhythmRoute
  '/typefall': typeof TypefallRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/leaderboard' | '/multiplayer' | '/rhythm' | '/typefall'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/leaderboard' | '/multiplayer' | '/rhythm' | '/typefall'
  id:
    | '__root__'
    | '/'
    | '/leaderboard'
    | '/multiplayer'
    | '/rhythm'
    | '/typefall'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LeaderboardRoute: typeof LeaderboardRoute
  MultiplayerRoute: typeof MultiplayerRoute
  RhythmRoute: typeof RhythmRoute
  TypefallRoute: typeof TypefallRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/typefall': {
      id: '/typefall'
      path: '/typefall'
      fullPath: '/typefall'
      preLoaderRoute: typeof TypefallRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rhythm': {
      id: '/rhythm'
      path: '/rhythm'
      fullPath: '/rhythm'
      preLoaderRoute: typeof RhythmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/multiplayer': {
      id: '/multiplayer'
      path: '/multiplayer'
      fullPath: '/multiplayer'
      preLoaderRoute: typeof MultiplayerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LeaderboardRoute: LeaderboardRoute,
  MultiplayerRoute: MultiplayerRoute,
  RhythmRoute: RhythmRoute,
  TypefallRoute: TypefallRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
