/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TypefallRouteImport } from './routes/typefall'
import { Route as ScoreboardRouteImport } from './routes/scoreboard'
import { Route as MultiplayerRouteImport } from './routes/multiplayer'
import { Route as IndexRouteImport } from './routes/index'

const TypefallRoute = TypefallRouteImport.update({
  id: '/typefall',
  path: '/typefall',
  getParentRoute: () => rootRouteImport,
} as any)
const ScoreboardRoute = ScoreboardRouteImport.update({
  id: '/scoreboard',
  path: '/scoreboard',
  getParentRoute: () => rootRouteImport,
} as any)
const MultiplayerRoute = MultiplayerRouteImport.update({
  id: '/multiplayer',
  path: '/multiplayer',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/multiplayer': typeof MultiplayerRoute
  '/scoreboard': typeof ScoreboardRoute
  '/typefall': typeof TypefallRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/multiplayer': typeof MultiplayerRoute
  '/scoreboard': typeof ScoreboardRoute
  '/typefall': typeof TypefallRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/multiplayer': typeof MultiplayerRoute
  '/scoreboard': typeof ScoreboardRoute
  '/typefall': typeof TypefallRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/multiplayer' | '/scoreboard' | '/typefall'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/multiplayer' | '/scoreboard' | '/typefall'
  id: '__root__' | '/' | '/multiplayer' | '/scoreboard' | '/typefall'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MultiplayerRoute: typeof MultiplayerRoute
  ScoreboardRoute: typeof ScoreboardRoute
  TypefallRoute: typeof TypefallRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/typefall': {
      id: '/typefall'
      path: '/typefall'
      fullPath: '/typefall'
      preLoaderRoute: typeof TypefallRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scoreboard': {
      id: '/scoreboard'
      path: '/scoreboard'
      fullPath: '/scoreboard'
      preLoaderRoute: typeof ScoreboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/multiplayer': {
      id: '/multiplayer'
      path: '/multiplayer'
      fullPath: '/multiplayer'
      preLoaderRoute: typeof MultiplayerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MultiplayerRoute: MultiplayerRoute,
  ScoreboardRoute: ScoreboardRoute,
  TypefallRoute: TypefallRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
